spring: 
  application:
    name: stream-rabbitmq-consumer-service   
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于binding的整合
          type: rabbit # 消息中间件类型
          environment: # 设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: 192.168.0.103
                port: 5672
                username: eric
                password: Eric_123321
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: exchange.stream # 表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设为text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          
eureka:
  client: #客户端注册进eureka服务列表内
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    lease-renewal-interval-in-seconds: 20 # 设置心跳的间隔时间，默认30
    lease-expiration-duration-in-seconds: 50 # 超过5秒间隔，默认90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 显示ip
    