spring: 
  application:
    name: stream-rabbitmq-consumer-service   
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于binding的整合
          type: rabbit # 消息中间件类型
          environment: # 设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: 192.168.0.103
                port: 5672
                username: eric
                password: Eric_123321
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: exchange.stream.eric # 表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设为text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          
    