aaa: 'aaa'

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.0.103}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:eric}
    password: ${RABBITMQ_PASSWORD:Eric_123321}
    virtual-host: ${RABBITMQ_VIRTUAL-HOST:/test}
  
    
#监控端点         
management:
  endpoints:
    web:
      exposure:
        include: "*"
     
eureka:
  instance:
    prefer-ip-address: true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${EUREKA_INSTANCE_IP-ADDRESS:127.0.0.1}
    #instance-id: ${server.address}:${spring.application.name}:${server.port} #指定实例id
    #instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    ##表示eureka clientl间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    lease-renewal-interval-in-seconds: 5
    #Expiration Seconds，表示eureka server至上一次收到cliente的心跳之后，等待下ー次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    #默认为 90 秒
    #1.如果该值太大，则很可能将流暈转发过去的时候，该instance已经不存活
    #2.如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉
    #3.该值至少应该大于lease Renewallntervalln Seconds
    lease-expiration-duration-in-seconds: 60