############ 公共配置

##RABBITMQ
RABBITMQ_HOST: 192.168.0.103
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: eric
RABBITMQ_PASSWORD: Eric_123321
RABBITMQ_VIRTUAL-HOST: /test

##eureka
EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://192.168.0.103:8761/eureka/    ##客户端
##EUREKA_INSTANCE_IP-ADDRESS: 127.0.0.1         
