
sss: 
  kkk: 'dev'
  
aaa: 'aaa'


spring:
 
    
  
  
    
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://192.168.0.103:3307/${spring.application.name}}
    username: root
    password: Eric_123321
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5    
  jpa:
    open-in-view: true
    hibernate:
    #更新或者创建数据表结构
      ddl-auto: update
    #控制台显示SQL
    show-sql: true
     


     

    
    
  redis:
    #配置redis单机模式
#    host: 127.0.0.1 
#    database: 0
#    port: 6379
#    password: 
#    timeout: 2000
    #配置redis集群模式
    #配置属性查看org.redisson.config.Config 
    cluster:
      nodes:
        - 192.168.0.103:6379
        - 127.0.0.1:6380
        - 127.0.0.1:6381
        - 127.0.0.1:6382
        - 127.0.0.1:6383
        - 127.0.0.1:6383
    lettuce:
      pool:
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认8
        max-idle: 10
        # 连接池中的最小空闲连接 默认0
        min-idle: 1    
  