##水平分表
spring:  
  shardingsphere: 
    props:
      sql:
        show: true
    datasource: 
      names: ds
        
      ds: 
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.0.103:3306/ds?serverTimezone=UTC&useSSL=false
        username: root
        password: Eric_123321
        max-active: 16

    sharding: 
      tables:
         
        t_news: 
          actual-data-nodes: ds.t_news_$->{1..2}
          table-strategy: 
            inline: 
              sharding-column: id
              algorithm-expression: t_news_$->{id % 2+1}
          key-generator: 
            column: id
            type: SNOWFLAKE
            props: 
              worker: 
                id: 123
