eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true #服务发现开关
    service-url: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${DEFAULTZONE:http://192.168.0.103:8761/eureka/}
#  instance:
#    prefer-ip-address: true  #将自己的ip地址注册到Eureka服务中
#    ip-address: ${IP_ADDRESS:127.0.0.1}
    #instance-id: ${spring.application.name}:${server.port} #指定实例id